source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in flex.gemspec.
gemspec

gem "puma"

gem "sqlite3"

gem "sprockets-rails"

group :development, :test do
  gem "factory_bot_rails"
  gem 'rspec-rails', '~> 7.0.0'
end

# Start debugger with binding.b [https://github.com/ruby/debug]
# gem "debug", ">= 1.0.0"
