plugins:
  - rubocop-rspec
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false

AllCops:
  Exclude:
    - "spec/dummy/node_modules/**/*"
    - "spec/dummy/public/**/*"
    - "spec/dummy/tmp/**/*"
    - "spec/dummy/log/**/*"
    - "spec/dummy/storage/**/*"
